### ISSUE TITLE
Infer error

### ISSUE THREAD

**Issue by JaggerZr** [yuyouyu32/BeyondDialogue#1]
你好，在用你的模型的
![屏幕截图 2024-11-01 164611](https://github.com/user-attachments/assets/e00213d1-df2f-4882-ba74-2b34f67aa388)
时候，发现推理报错，是否我这边下载的模型出现问题。

还有一个问题，您的[Roles Info.xlsx]是如何制作的，可否指导一下。

**Comment by yuyouyu32** [comment]
【推理问题】
目前看起来模型应该是没有问题，是transformer的版本问题，我查到相关的链接表示降低版本可以避免这个问题，这是我使用的transformer版本供参考：
transformers                  4.41.2
transformers-stream-generator 0.0.5

【Role Info.xlsx文件制作】
下面是一些我之前收集时用到的方法：
1. 收集之前RP论文的角色profile，作为参考（如Character Eval，TimeChar等）
2. 爬取一些开源的小说网站，人工定义角色和profile

**Comment by JaggerZr** [comment]
谢谢你的回答，你这篇工作非常有参考性。
